# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6ad5a1fdf1dd8ea0e0d1237b87294c784a194ff45de4ab38586742c207a931926c6b078eb55b0fb6dcd268d76ed8f1adead29f78401da3ecc5cf760f87a98a46

test:
  secret_key_base: dae08226b61dfc25fbc813881cacacb5d46be1c2a622b5a017f6d0652d830e05db63eca7e902bb756df49a3fb6ded7cb501395d107297fa5c5be8b63ae3834f1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
